/*==========================================================
  FOOD DONATION MANAGEMENT SYSTEM
  MODULE: SQL QUERIES AND LOGIC
==========================================================*/

/* 1. INSERT SAMPLE DATA */

INSERT INTO DONOR VALUES
(101, 'Ramesh Kumar', '9876543210', 'Bangalore');

INSERT INTO RECEIVER VALUES
(201, 'Ananya Trust', '9876501234', 'Bangalore');

INSERT INTO FOOD VALUES
(301, 'Veg Biryani', 50,
 TO_DATE('15-05-2026','DD-MM-YYYY'),
 101, 'Available');


/* 2. DISPLAY AVAILABLE FOOD */

SELECT FOOD_ID,
       FOOD_NAME,
       QUANTITY,
       EXPIRY_DATE,
       STATUS
FROM FOOD
WHERE STATUS = 'Available';


/* 3. CREATE FOOD REQUEST */

INSERT INTO REQUEST
(REQUEST_ID, RECEIVER_ID, FOOD_ID, REQUEST_DATE, STATUS)
VALUES
(401, 201, 301, SYSDATE, 'Pending');


/* 4. VIEW ALL REQUESTS */

SELECT R.REQUEST_ID,
       RC.RECEIVER_NAME,
       F.FOOD_NAME,
       F.QUANTITY,
       R.REQUEST_DATE,
       R.STATUS
FROM REQUEST R
JOIN RECEIVER RC
ON R.RECEIVER_ID = RC.RECEIVER_ID
JOIN FOOD F
ON R.FOOD_ID = F.FOOD_ID;


/* 5. APPROVE REQUEST */

UPDATE REQUEST
SET STATUS = 'Approved'
WHERE REQUEST_ID = 401;


/* 6. DONOR-WISE DONATION REPORT */

SELECT D.DONOR_NAME,
       COUNT(F.FOOD_ID) AS TOTAL_DONATIONS,
       SUM(F.QUANTITY) AS TOTAL_QUANTITY
FROM DONOR D
LEFT JOIN FOOD F
ON D.DONOR_ID = F.DONOR_ID
GROUP BY D.DONOR_NAME;


/* 7. MOST ACTIVE RECEIVERS */

SELECT RC.RECEIVER_NAME,
       COUNT(R.REQUEST_ID) AS TOTAL_REQUESTS
FROM RECEIVER RC
JOIN REQUEST R
ON RC.RECEIVER_ID = R.RECEIVER_ID
GROUP BY RC.RECEIVER_NAME
ORDER BY TOTAL_REQUESTS DESC;


/* 8. CREATE VIEW */

CREATE OR REPLACE VIEW AVAILABLE_FOOD_VIEW AS
SELECT F.FOOD_ID,
       F.FOOD_NAME,
       F.QUANTITY,
       F.EXPIRY_DATE,
       D.DONOR_NAME,
       D.PHONE
FROM FOOD F
JOIN DONOR D
ON F.DONOR_ID = D.DONOR_ID
WHERE F.STATUS = 'Available';


/* 9. DISPLAY VIEW */

SELECT * FROM AVAILABLE_FOOD_VIEW;


/* 10. CREATE TRIGGER */

CREATE OR REPLACE TRIGGER TRG_UPDATE_FOOD_STATUS
AFTER UPDATE OF STATUS ON REQUEST
FOR EACH ROW
WHEN (NEW.STATUS = 'Approved')
BEGIN
    UPDATE FOOD
    SET STATUS = 'Allocated'
    WHERE FOOD_ID = :NEW.FOOD_ID;
END;
/

/* 11. CHECK FINAL FOOD STATUS */

SELECT * FROM FOOD;
