CREATE TABLE DONOR (
    DONOR_ID NUMBER PRIMARY KEY,
    DONOR_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) UNIQUE,
    CITY VARCHAR2(50)
);

CREATE TABLE RECEIVER (
    RECEIVER_ID NUMBER PRIMARY KEY,
    RECEIVER_NAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) UNIQUE,
    CITY VARCHAR2(50)
);

CREATE TABLE FOOD (
    FOOD_ID NUMBER PRIMARY KEY,
    FOOD_NAME VARCHAR2(100) NOT NULL,
    QUANTITY NUMBER NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    DONOR_ID NUMBER,
    STATUS VARCHAR2(20) DEFAULT 'Available',
    FOREIGN KEY (DONOR_ID) REFERENCES DONOR(DONOR_ID)
);

CREATE TABLE REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    RECEIVER_ID NUMBER,
    FOOD_ID NUMBER,
    REQUEST_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) DEFAULT 'Pending',
    FOREIGN KEY (RECEIVER_ID) REFERENCES RECEIVER(RECEIVER_ID),
    FOREIGN KEY (FOOD_ID) REFERENCES FOOD(FOOD_ID)
);
